import { useState, useEffect } from "react"
import { useSession } from "next-auth/client"
import Head from 'next/head'
import Header from "../components/Header";
import AddRequestForm from "../components/AddRequestForm/AddRequestForm";
import LoginGate from "../components/LoginGate";

export default function Requests() {
    const [session, loading] = useSession();
    console.log(session)
    return (
        <>
            <Head>
                <title>Wir Helfen</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href='https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900' rel="stylesheet" />
            </Head>
            <Header session={session} />
            <div className="relative bg-white overflow-hidden">
                <div className="max-w-7xl mx-auto">
                    <div className="relative z-10 pb-8 bg-white sm:pb-16 md:pb-20 lg:w-full lg:pb-28 xl:pb-32">
                        <main className="mx-auto max-w-7xl px-4 sm:mt-12 sm: pt-10 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
                        <div className="flex flex-wrap -mx-1 overflow-hidden sm:-mx-1 md:-mx-1 lg:-mx-1 xl:-mx-1">
                                {!session && (
                                    <LoginGate/>
                                )}
                                {session && (
                                    <AddRequestForm/>
                                )}
                            </div>
                        </main>
                    </div>
                    </div>
                </div>
        </>
    )
}