import Head from 'next/head'
import React from 'react'
import { useSession } from 'next-auth/client'
import Header from '../components/Header'
import HeroSection from '../components/HeroSection'
import { Footer } from '../components/Footer'

export default function Home() {
  const [session, loading] = useSession()

  return (
    <div>

      <Head>
        <title>Wir Helfen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href='https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900' rel="stylesheet" />
      </Head>

      <Header session={session}></Header>
      <HeroSection></HeroSection>
      <Footer> </Footer>
    </div>
  )
}
